import os
from playwright.sync_api import sync_playwright
from markdown_it import MarkdownIt

def generate_pdf(report_md, filename):
    """
    Converte o relatório Markdown em um PDF Cyberpunk Profissional.
    """
    md = MarkdownIt()
    html_content = md.render(report_md)
    
    # CSS para deixar o PDF bonito (Estilo Relatório Hacker)
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Courier New', monospace; padding: 40px; color: #1a1a1a; }}
            h1 {{ border-bottom: 3px solid #00ff00; padding-bottom: 10px; color: #004400; }}
            h2 {{ background-color: #f0f0f0; padding: 5px; border-left: 5px solid #00ff00; margin-top: 30px; }}
            strong {{ color: #d63384; }}
            code {{ background: #eee; padding: 2px 5px; border-radius: 3px; }}
            .footer {{ margin-top: 50px; font-size: 10px; color: #666; text-align: center; border-top: 1px solid #ccc; padding-top: 10px; }}
            .logo {{ font-size: 24px; font-weight: bold; color: #00ff00; background: black; padding: 10px; display: inline-block; }}
        </style>
    </head>
    <body>
        <div class="logo">PERFSCAN v6.0 // CONFIDENTIAL</div>
        <br><br>
        {html_content}
        <div class="footer">Generated by PerfScan God Mode • Automated Audit System</div>
    </body>
    </html>
    """
    
    # Salva o PDF usando Playwright
    pdf_path = filename.replace(".md", ".pdf")
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        page.set_content(full_html)
        page.pdf(path=pdf_path, format="A4")
        browser.close()
        
    return pdf_path